DROP TABLE IF EXISTS eventos;
DROP TABLE IF EXISTS presenca_evento;

CREATE TABLE IF NOT EXISTS eventos (id INTEGER(5) PRIMARY KEY AUTO_INCREMENT, code VARCHAR(60) NOT NULL, name VARCHAR(60) NOT NULL, date VARCHAR(60) NOT NULL, begin_event VARCHAR(60) NOT NULL, end_event VARCHAR(60) NOT NULL, place VARCHAR(60) NOT NULL);
CREATE TABLE IF NOT EXISTS presenca_evento (id INTEGER(5) PRIMARY KEY AUTO_INCREMENT, code VARCHAR(60) NOT NULL, nome VARCHAR(60) NOT NULL, matricula VARCHAR(60) NOT NULL, email VARCHAR(60) NOT NULL);
